version: '2'
services:
  reverseproxy:
    build: .
    ports: ['8080:8080']
    restart: always
  apache:
    depends_on: [reverseproxy]
    image: httpd:alpine
    restart: always
  nginx:
    depends_on: [reverseproxy]
    image: nginx:alpine
    restart: always

